Feat #27 automatic checkout (draft)
galezra/lusha-register-extension pull request #36
Opened 2024-01-12 21:53 UTC by Matanga1-2

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?
Today we don't have behavior at all in the checkout page

Issue Number: #27 

## What is the new behavior?

This PR extends https://github.com/galezra/lusha-register-extension/pull/35
Main changes so far are 
- Extension works on billing URLs
- Added new CheckoutForm, CheckoutPage, and CheckoutElements
- Separated Form to SignupForm and CheckoutForm
- Adjusted Lugister button with z-index to show over banners

## Other information
Example screenshot -
<img width="1491" alt="image" src="https://github.com/galezra/lusha-register-extension/assets/24847398/15897b94-6a14-4028-ac6e-3c0be74678fd">

For now, I didn't extend the extension form and will use hard-coded values.
Once working, we can extend with tabs to support segmentation, signup, checkout, and more.

2024-01-12 21:55 UTC, Matanga1-2 commented
@galezra @Ivgesha this PR extends https://github.com/galezra/lusha-register-extension/pull/35
I started writing my code and then merged some of @Ivgesha changes. Great start!

I'm stuck with the useForm() as it is not separated to support both signup & checkout.
@galezra appreciate your feedback if the approach I did so far aligns with your vision.

2024-01-12 22:01 UTC, Ivgesha commented
@Matanga1-2 
Good job! 
As for useForm(), you are correct. Currently it supports only registration. 
We should consider making it more generic.

2024-01-12 22:20 UTC, Ivgesha commented
@Matanga1-2  @galezra 
I believe we have made commendable progress so far.
Now might be a good time to assess whether we can integrate this PR without compromising readability, as additional code could make it more challenging to follow. Additionally, I propose a strategic decomposition of the bullet points delineated by @galezra in the corresponding [issue](https://github.com/galezra/lusha-register-extension/issues/27#issuecomment-1888868416), thereby transforming them into actionable tasks. This methodical approach will contribute to a more streamlined and manageable workflow.

2024-01-12 22:32 UTC, galezra commented
> @Matanga1-2 @galezra I believe we have made commendable progress so far. Now might be a good time to assess whether we can integrate this PR without compromising readability, as additional code could make it more challenging to follow. Additionally, I propose a strategic decomposition of the bullet points delineated by @galezra in the corresponding [issue](https://github.com/galezra/lusha-register-extension/issues/27#issuecomment-1888868416), thereby transforming them into actionable tasks. This methodical approach will contribute to a more streamlined and manageable workflow.

Thanks, @Ivgesha! 
I totally agree. As I said [here](https://github.com/galezra/lusha-register-extension/issues/27#issuecomment-1890064401), I'm making small changes to make it easier to add the new PR by you and Matan

2024-01-13 09:47 UTC, Ivgesha commented on manifest.config.ts
> +      ],
We can add 
"https://billing.lusha.com/*" for production access also.

2024-01-13 09:47 UTC, Ivgesha commented on src/components/Header/index.tsx
> +      <Title>Lugister - Box of Wonders (test)</Title>
Dont forget to remove the (test)

2024-01-13 09:50 UTC, Ivgesha commented on src/constants/global.ts
> +export const DEFAULT_SIGNUP_FORM_VALUES: SignupForm = {
Good job for renaming it to a suitable name!

2024-01-13 10:04 UTC, Ivgesha requested changes
Very good job! 
If it possible, let's temporarily conceal the 'Lugister' button currently visible on the checkout page, as it is not yet ready for deployment.
Also, on get-page-factory, consider flagging out the if statement when ever the URI is checkout. If not, we may start the logic in "start()" function. 

To implement this, we can employ conditional statements set to evaluate as false within pivotal workflows, or alternatively, leverage config settings for a more seamless integration.

Do consider using Config (https://www.npmjs.com/package/config) as it will let you add properties like: 
featureCodes: {
  automatedCheckout: true/false
},

and we can use it in the code as: Config,get('featureCodes.automatedCheckout')

2024-01-13 13:46 UTC, galezra commented
Hi @Ivgesha and @Matanga1-2,
I've completed the refactor as outlined in this pull request: #37 . I'd appreciate it if you could both review the changes.

Once the review is done and merged, @Matanga1-2, please feel free to proceed with merging form master the changes to your branch. Also, as you work on your draft PR #36 , kindly ensure that the new class conventions for pages and elements architecture (extends, local storage, private members, etc)

2024-01-14 07:44 UTC, Matanga1-2 commented on manifest.config.ts
> +      ],
@Ivgesha production is problematic since -
1. Stripe can identify bot behavior and block the process
2. Storing real credit card number is not a good practice
I suggest starting with Stage and then see where it takes us

2024-01-14 07:53 UTC, Ivgesha commented
> Hi @Ivgesha and @Matanga1-2, I've completed the refactor as outlined in this pull request: #37 . I'd appreciate it if you could both review the changes.
> 
> Once the review is done and merged, @Matanga1-2, please feel free to proceed with merging form master the changes to your branch. Also, as you work on your draft PR #36 , kindly ensure that the new class conventions for pages and elements architecture (extends, local storage, private members, etc)

2024-01-14 07:55 UTC, Ivgesha commented
@galezra 
Very good job! 
Approved your [PR](https://github.com/galezra/lusha-register-extension/pull/37)

2024-01-14 08:05 UTC, Matanga1-2 commented
> Very good job! If it possible, let's temporarily conceal the 'Lugister' button currently visible on the checkout page, as it is not yet ready for deployment. Also, on get-page-factory, consider flagging out the if statement when ever the URI is checkout. If not, we may start the logic in "start()" function.
> 
> To implement this, we can employ conditional statements set to evaluate as false within pivotal workflows, or alternatively, leverage config settings for a more seamless integration.
> 
> Do consider using Config (https://www.npmjs.com/package/config) as it will let you add properties like: featureCodes: { automatedCheckout: true/false },
> 
> and we can use it in the code as: Config,get('featureCodes.automatedCheckout')

Thank you @Ivgesha , I added this behavior for now using a global const

2024-01-14 08:39 UTC, Ivgesha commented on manifest.config.ts
> +      ],
Good point!

2024-01-14 08:42 UTC, Ivgesha approved these changes

2024-01-14 08:47 UTC, closed without merging